const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/reis', { useNewUrlParser: true, useUnifiedTopology: true });

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
  // we're connected!
  console.log('CONNECTED TO DATABASE!')
});
//fit: 1 to 5
//stars: 1 to 5

const reiSchema = mongoose.Schema({
  id: Number,
  username: String,
  product_id: Number,
  date: String,
  title: String,
  stars: Number,
  review: String,
  img: String,
  caption: String,
  recommend: Boolean,
  readReviews: Boolean,
  feedBack: String,
  email: String,
  location: String,
  purchaseLocation: Number,
  fit: Number,
  helpful_yes: Number,
  helpful_no: Number,
  appropriate: Boolean
});

let REI = mongoose.model('REI', reiSchema);

REI.insertMany([{
  id: 1,
  username: "Tinman1974",
  product_id: 1,
  date: "6 years ago",
  title: "Excellent value in a rain jacket",
  stars: 5,
  review: "I recently got to test this jacket on a Joshua Tree hiking trip and I’m really impressed. If you need something that’s not to heavy or overly hot this is the jacket for you.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "tinman@gmail.com",
  location: "Los Angeles, CA",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 5,
  helpful_no: 0,
  appropriate: false
}, {
  id: 2,
  username: "JJ4RNR",
  product_id: 1,
  date: "5 years ago",
  title: "Unfortunately not waterproof enough",
  stars: 3,
  review: "Bought this and a matching one for my fiancée for a mountain climb. It performed well in misty, steady rain initially but was thoroughly soaked through for both of us by the end. Definitely not something you’d want to trust in a torrential downpour but probably a good jacket for walking around in the city. I love though, REI and look forward to seeing what they release/tweak next.",
  img: "https://reiimages.s3-us-west-1.amazonaws.com/user_images/jacket1.jpeg",
  caption: "Moisture inside of jacket",
  recommend: false,
  readReviews: true,
  feedBack: "fb",
  email: "JJ4RNR@gmail.com",
  location: "New York, NY",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 10,
  helpful_no: 2,
  appropriate: false
}, {
  id: 3,
  username: "HKYwill",
  product_id: 1,
  date: "9 months ago",
  title: "Excellent value in a rain jacket",
  stars: 5,
  review: "I’ve been looking for a trustworthy rain jacket that I don’t have to mortgage my house for. When I saw this jacket online, I thought it might fit the bill, so I decided to pop into an REI to check it out. While it’s missing some of the bells and whistles of pricier options, like “pit zips”, that’s kind of the point. It’s waterproof, windproof, and made of a seemingly durable material, with minimal branding, all for $50. I wore it out of the store and into a driving rain to walk back to my car, and stayed dry all the way. The next day, a stiff wind didn’t affect me at all. The jacket does run large; I typically wear XL in most clothing, including REI’s products, but I had room to layer a puffy underneath even when sizing down to a large. Size down accordingly.",
  img: "https://reiimages.s3-us-west-1.amazonaws.com/user_images/jacket2.jpeg",
  caption: "Dodging the wet in Canada's NWT",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "HKYwill@gmail.com",
  location: "New York, NY",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 20,
  helpful_no: 6,
  appropriate: false
}, {
  id: 4,
  username: "LGGO",
  product_id: 1,
  date: "7 months ago",
  title: "Great Jacket, good price",
  stars: 5,
  review: "Comfortable and stylish, couldn't imagine receiving a better product at the entry level of rain gear.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "LGGO@yahoo.com",
  location: "White Plains, NY",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 10,
  helpful_no: 1,
  appropriate: false
}, {
  id: 5,
  username: "rpkeskar",
  product_id: 1,
  date: "4 months ago",
  title: "Lightweight and good quality",
  stars: 4,
  review: "Loved using this on my Euro trip. Rolls into a small shape, covers up pretty well. Loved the blue color. It's going to be my new best friend on rainy days.",
  img: "https://reiimages.s3-us-west-1.amazonaws.com/user_images/jacket3.jpeg",
  caption: "Inside of jacket where a light rain soaked through",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "rpkeskar@gmail.com",
  location: "New York, NY",
  purchaseLocation: 1,
  fit: 2,
  helpful_yes: 22,
  helpful_no: 0,
  appropriate: false
}, {
  id: 6,
  username: "MCzArt",
  product_id: 1,
  date: "2 months ago",
  title: "Great jacket at an affordable price",
  stars: 5,
  review: "The jacket is not super flashy or feature rich, but it gets the job done. I have had it in multiple rain storms, on a boat, and have used it as a wind breaker. I have never felt like I am overheating as it moves air around my body nicely. The pockets are a decent size and despite the lack of fasteners, they seem to hold things pretty securely.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "MCzArt@gmail.com",
  location: "Seattle, WA",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 10,
  helpful_no: 1,
  appropriate: false
}, {
  id: 7,
  username: "Kratzat",
  product_id: 1,
  date: "1 month ago",
  title: "Light and great for walks",
  stars: 5,
  review: "great buy at a great price. Have been really enjoying it.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "Kratzat@gmail.com",
  location: "New York, NY",
  purchaseLocation: 1,
  fit: 2,
  helpful_yes: 4,
  helpful_no: 0,
  appropriate: false
}, {
  id: 8,
  username: "JustDave",
  product_id: 1,
  date: "1 month ago",
  title: "Not useful in the Alleghenies",
  stars: 2,
  review: "I bought this rain jacket about a year ago as it was very lightweight with good fit. I used it around town and on several short 1 to 4 day backpacking trips and it seemed to work fine, although it didn't really get put to the test. However, on a recent 9 day trip to West Virginia, I encountered rainy conditions several days. I found that under backpacking conditions, the fabric seemed to wet out pretty readily and I had wet arms and shoulders. In short, this jacket may be fine where rain is light and rare, but not in spring in the Alleghenies or the northwest.",
  img: "https://reiimages.s3-us-west-1.amazonaws.com/user_images/jacket4.jpeg",
  caption: "Kept the rain out but got hot quick",
  recommend: false,
  readReviews: false,
  feedBack: "fb",
  email: "JustDave@gmail.com",
  location: "San Francisco, CA",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 55,
  helpful_no: 2,
  appropriate: false
}, {
  id: 9,
  username: "El pasajero",
  product_id: 1,
  date: "25 days ago",
  title: "New Gold Standard for Packable Shell",
  stars: 5,
  review: "Background: I have used this product >1 year in rains (drizzle to downpour) with temps ranging from upper 30's to 90's F. Given its compactness it's always in my bag. This is my 4th shell ever and my most expensive to date.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "fb",
  email: "el_pasajero@gmail.com",
  location: "Chicago, IL",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 15,
  helpful_no: 2,
  appropriate: false
}, {
  id: 10,
  username: "marinesoup",
  product_id: 1,
  date: "20 days ago",
  title: "awesome for motorcycle and camping",
  stars: 4,
  review: "this is the best jacket for rain i have ever purchased. breathability is real and works. no internal moisture build up and no rain penetrates. and it packs so small and is light. have had this for almost two years. it is durable and it love the hood and pull in the back to tighten around my head for full coverage. love the lime green color for night time visibility.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "fb",
  email: "marinesoup@gmail.com",
  location: "Houston, TX",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 40,
  helpful_no: 9,
  appropriate: false
}, {
  id: 11,
  username: "MammothSniper18",
  product_id: 1,
  date: "16 days ago",
  title: "Used to complete 3 day sniper match",
  stars: 3,
  review: "Used during a 3-day field sniper match. All gear for three days including rifle and ammo needed to be carried to each stage, with camping at night. Lightweight gear a must. Purchased the Helium jacket and pants with this in mind, but also hoped for a dry weekend. Well, heavy rains for the first 24 hours of the competition. Jacket material repelled rain well and protected clothing underneath, but did wet out within a couple of hours. On the upside when the sun did finally show the lightweight material dried extremely fast. Wore the pants the entire match to shrug off mud when rucking and crawling at stages, the lightweight material held up fine.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "MammothSniper18@gmail.com",
  location: "Philadelphia, PA",
  purchaseLocation: 1,
  fit: 4,
  helpful_yes: 7,
  helpful_no: 1,
  appropriate: false
}, {
  id: 12,
  username: "brandongur",
  product_id: 1,
  date: "14 days ago",
  title: "Best rain shell I have owned to date",
  stars: 3,
  review: "This is my ultra-light quiver shell. I take this everywhere all year long. It compresses to an incredibly small size, so its in my bag where ever I go for rain or snow. In the winter, Ill toss it over my OR Transcendent puffy to keep warm and dry on the street, on belay, or on a speedy ascent on a weekend crag. In the Spring and summer, its the perfect weight to keep dry without sweating your clothes out. Ill keep it in my climbing or light hiking pack, and will throw it on mid-route when an unexpected rain comes through. Pairs exceptionally well with the OR Ferrosi hoody for Spring and Fall climbing when a blast of wet cold can shoot in on you. It looks great, so it goes with me on the town or to Seattle sports events where rain is a constant factor. It has no frills and or basic features, but that's the whole point of a bomber, ultra-light rain jacket.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "brandongur@gmail.com",
  location: "San Diego, CA",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 41,
  helpful_no: 5,
  appropriate: false
}, {
  id: 13,
  username: "Neil Provo",
  product_id: 1,
  date: "10 days ago",
  title: "Ultralight shell for those unexpected storms",
  stars: 5,
  review: "The size of an apple and the weight of a fly box, the Helium2 jacket will fit into every outdoorsman kit out there! You never know when that perfect blue day in the mountains will turn into a dreadful wet and cold retreat. Weather your skiing/snowboarding, biking, fishing, camping, or climbing, with packable gear this light there's no reason to get stuck without proper weather protection when sky decides to unleash. Toss it in your pack and never look back!",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "Neil_Provo@gmail.com",
  location: "San Antonio, TX",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 30,
  helpful_no: 1,
  appropriate: false
}, {
  id: 14,
  username: "pegoodman",
  product_id: 1,
  date: "7 days ago",
  title: "Not useful in the Alleghenies",
  stars: 2,
  review: "I bought this rain jacket about a year ago as it was very lightweight with good fit. I used it around town and on several short 1 to 4 day backpacking trips and it seemed to work fine, although it didn't really get put to the test. However, on a recent 9 day trip to West Virginia, I encountered rainy conditions several days. I found that under backpacking conditions, the fabric seemed to wet out pretty readily and I had wet arms and shoulders. In short, this jacket may be fine where rain is light and rare, but not in spring in the Alleghenies or the northwest.",
  img: "",
  caption: "",
  recommend: false,
  readReviews: false,
  feedBack: "fb",
  email: "pegoodman@gmail.com",
  location: "San Jose, CA",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 0,
  helpful_no: 3,
  appropriate: false
}, {
  id: 15,
  username: "vladik",
  product_id: 1,
  date: "5 days ago",
  title: "Not waterproof",
  stars: 1,
  review: "This is great for short exposure in light rain, however it's not waterproof. I got soaked on several occasions for prolonged hiking in rain. It packs nicely small. Convenient for short bike rides in rain. Not serious waterproof jacket.",
  img: "url",
  caption: "Beta AR on Mount Washington",
  recommend: false,
  readReviews: true,
  feedBack: "fb",
  email: "vladik@gmail.com",
  location: "Denver, CO",
  purchaseLocation: 1,
  fit: 5,
  helpful_yes: 10,
  helpful_no: 0,
  appropriate: false
}, {
  id: 16,
  username: "NWDude",
  product_id: 1,
  date: "1 day ago",
  title: "Superlight, yet Burly",
  stars: 5,
  review: "I've used my helium jacket in far-flung mountain environments, including remote backcountry climbs. It's obviously light and packable, but I have been consistently impressed that it is very durable and keeps me 100% dry.",
  img: "url",
  caption: "Beautiful color!!",
  recommend: true,
  readReviews: false,
  feedBack: "fb",
  email: "NWDude@gmail.com",
  location: "Detroit, MI",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 35,
  helpful_no: 6,
  appropriate: false
}, {
  id: 17,
  username: "Phil",
  product_id: 2,
  date: "10 days ago",
  title: "Great Jacket for AT Thru Hike 2017",
  stars: 5,
  review: "Used this jacket for 6 months during my 2017 AT thru hike.  During cold weather, it got used just about every day.  It was surprisingly warm and insulated quite well even when it was wet.  I wore my rain coat over it several times to block the wind.  I used the jacket in 10 deg temps in the Smokey's and I stayed warm.  I abused the jacket about every way possible and it's still in good shape.  It got drug over rocks, thru trees and brush.  It got rained on and it didn't always get washed per the instructions.  There's not any rips or tears and while it doesn't look like a new jacket any more, I can't justify replacing it either.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "fb",
  email: "Phil@gmail.com",
  location: "Los Angeles, Ca",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 145,
  helpful_no: 1,
  appropriate: false
}, {
  id: 18,
  username: "eliot",
  product_id: 2,
  date: "1 month ago",
  title: "great jacket but wears out",
  stars: 4,
  review: "These are great jackets but I have found that they wear out if not treated carefully. I'm on my third one, and I use it primarily for warmth in camp, when taking breaks hiking, etc. With the previous two, I made the mistake of treating them as jackets for everyday wear; over time, the quilting stitches started to go on both (cosmetic problem only, at least initially), and the zipper wore out on one. I tend to be hard on clothing, and I think making any jacket light and packable involves some compromises on durability. But this fits me better than any of the others that REI stocks (it's not super-slim, and neither am I) and it;s still a great jacket.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "eliot@yahoo.com",
  location: "",
  purchaseLocation: 1,
  fit: 4,
  helpful_yes: 18,
  helpful_no: 4,
  appropriate: false
}, {
  id: 19,
  username: "Ebris",
  product_id: 2,
  date: "5 months ago",
  title: "Light weight, warm but......",
  stars: 3,
  review: "I have to say, I really love this jacket overall. It’s light and keeps me warm here in oregon. My only complaint and concern is that for the price, I’ve had to return one already because the thread was pulling out and for a $200 dollar jacket that’s not something you expect, especially when I only wear it around town. I haven’t hiked or put this jacket through the ringer at all. I returned the first one and exchanged it for another one come to find out I found another thread pulling out. I’m torn because of the price of this jacket. I’m debating just returning it altogether and going with a different brand.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "Ebris@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 2,
  helpful_yes: 91,
  helpful_no: 21,
  appropriate: false
}, {
  id: 20,
  username: "DandyBoho",
  product_id: 2,
  date: "2 years ago",
  title: "Close to perfection, but material is so thin.",
  stars: 4,
  review: "So many minimalist bloggers and vloggers give this jacket such high praise. I don’t recall ever hearing a bad word about it. So, I decided to give it a try. It’s wonderful at keeping you warm, especially when layered. I work outdoors year-round, and have worn this jacket (with some extra layers) almost everyday this winter. No complaints there. My only complaint is that the shell material is so thin that it rips so easily, ending up with little tufts of white polyester poking out. Lightly brushing a broken twig put a hole in my arm. A dog jumping up to put its front paws on my waist led to a couple more. Etc. I would expect a bit better quality for the price. If the material was a little tougher it would be perfect.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "DandyBoho@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 26,
  helpful_no: 2,
  appropriate: false
}, {
  id: 21,
  username: "Bearcat85",
  product_id: 2,
  date: "1 year ago",
  title: "Most versatile insulating jacket out there",
  stars: 5,
  review: "The jacket is perfect for 25-50 degree weather and can go colder if layered properly. While very thin and almost weightless, the jacket seems to have the ability to adapt to the temperature around you and make you forget you are wearing it.  Perfect for wearing under waders in cool to cold climates.  While in Alaska, noticed that 75%+ of the fishing guides have one (the hoodie version for fast boating). Liked it so much that I bought vest too. Both compress down to almost nothing for easy packing.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Bearcat85@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 81,
  helpful_no: 3,
  appropriate: false
}, {
  id: 22,
  username: "LordYolo",
  product_id: 2,
  date: "12 days ago",
  title: "So Far So Good(only 3 months)",
  stars: 5,
  review: "I bought the jacket because Patagonia promises environmentally friendly practices and products that will last for years. I’ve only had the product a short time and it is great.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "LordYolo@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 11,
  helpful_no: 2,
  appropriate: false
}, {
  id: 23,
  username: "Dave",
  product_id: 2,
  date: "4 months ago",
  title: "Great jacket, fit is a bit slim",
  stars: 4,
  review: "I've used my helium jacket in far-flung mountain environments, including remote backcountry climbs. It's obviously light and packable, but I have been consistently impressed that it is very durable and keeps me 100% dry.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "Dave@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 86,
  helpful_no: 29,
  appropriate: false
}, {
  id: 24,
  username: "LC1984",
  product_id: 2,
  date: "6 months ago",
  title: "My husband lives in this jacket!",
  stars: 5,
  review: `I bought this jacket for my husband a few months ago, and he absolutely loves it! It's warm enough that he can wear it over a sweatshirt or heavy flannel shirt if it's not too ungodly cold outside. When it is really cold (we've been blessed with -40F wind chills the past couple of weeks), he layers it under a heavier winter coat. For reference, he wears a size large and he's about 5'11" and 200 lbs.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "LC1984@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 49,
  helpful_no: 3,
  appropriate: false
}, {
  id: 25,
  username: "DeeetroitAnthony",
  product_id: 2,
  date: "7 months ago",
  title: "Absolutely the BEST!",
  stars: 5,
  review: "I was up in Northern MI last weekend and the 45 degree mornings had me trying this out for the first time.  I am 6’4” and I typically have issues with sleeve length. Not a problem with this jacket. It fits so nicely across the shoulders that the Large was great. I am a beanpole too, so the shaping and the cut was perfect too. I only had on a t-shirt under and I was plenty warm. So at 40 degrees I didn’t even have to layer up and then shed as we hit 50/55. We were on and off boats and I never was cold and never had an issue with the splash that we would get randomly from the waves.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "DeeetroitAnthony@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 4,
  helpful_no: 1,
  appropriate: false
}, {
  id: 26,
  username: "James",
  product_id: 2,
  date: "7 days ago",
  title: "Go-to Spring/Fall coat",
  stars: 5,
  review: "I've been looking for a medium weight coat with a hood, and this one seems like a winner!  It's fuzzy on the inside, waterproof on the outside, and plenty warm for Spring and Fall (I haven't tried it in Winter yet).",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "James@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 4,
  helpful_no: 0,
  appropriate: false
}, {
  id: 27,
  username: "aarbint2013",
  product_id: 2,
  date: "1 year ago",
  title: "Great every day coat",
  stars: 5,
  review: "Awesome coat, only problem is that the feathers and material is so fine that feather pop through pretty often. I’ve owned the coat for almost a month and had about a dozen feathers come through. I just wear it back and forth to work right now. Thankfully there’s a Patagonia store in Pittsburgh and they were really helpful with showing me NOT TO PULL feathers out, but pushing them back in. Pulling them out only makes the hole larger and brings more feathers out.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "aarbint2013@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 10,
  helpful_no: 0,
  appropriate: false
}, {
  id: 28,
  username: "kevin",
  product_id: 2,
  date: "10 months ago",
  title: "Good warmth for cold mornings",
  stars: 4,
  review: "compared this vs down sweater and this has more loft in the down so that I found it to be much warmer for walking to work in the morning in Spokane. I liked the elastic cuffs inside the end of the sleeve to capture warmth and the fleece lined pockets versus what the down sweater had. Perfect for keeping you warm in mid to low 20s with wind and just a tee shirt underneath.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "kevin@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 6,
  helpful_no: 1,
  appropriate: false
}, {
  id: 29,
  username: "Bronco_1984",
  product_id: 2,
  date: "11 months ago",
  title: "Warm and Comfortable",
  stars: 5,
  review: "Wore this up in Whitefish, MT one week with temps in the single digits, below freezing with wind chill.  Never felt cold.  Very lightweight and comfortable.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "Bronco_1984@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 5,
  helpful_yes: 44,
  helpful_no: 7,
  appropriate: false
}, {
  id: 30,
  username: "David_G",
  product_id: 2,
  date: "1 day ago",
  title: "Great Winter Friend",
  stars: 5,
  review: "Excellent as a stand alone winter coat. Keeps the cold off me and allows plenty of movement for all sorts of outdoor activities including the evening dog-walk in the cold night air. It also is a perfect layer for a parka in the rain. Skip the 3-in-1 and use the Silent Down Jacket and your favorite parka as separates. It has the usual solid Patagonia construction while being light weigh and stylish which is not always easy to find today.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "David_G@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 10,
  helpful_no: 0,
  appropriate: false
}, {
  id: 31,
  username: "Raton",
  product_id: 2,
  date: "5 months ago",
  title: "Silent Down Jacket",
  stars: 1,
  review: "Jacket after wearing 5 times seems to be at a lost of down. Have only worn to work. Poor quality from Patagonia.",
  img: "",
  caption: "",
  recommend: false,
  readReviews: true,
  feedBack: "",
  email: "Raton@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 4,
  helpful_yes: 16,
  helpful_no: 2,
  appropriate: false
}, {
  id: 32,
  username: "Kurt70",
  product_id: 3,
  date: "5 years ago",
  title: "Turns winter into summer",
  stars: 4,
  review: "I bought this awesome puffy at REI in San Antonio. Yes I know, San Antonio is a warm climate but I live in Arkansas.  I have already put the puffy to use in mild temperatures (27 degrees) and it was very comfortable.  Other who had similar coats in another brand were COLD, hehe!  The coat is very quiet and I normally wear a XL and I bought the XL and it has plenty of room to layer if so desired.  I give this Patagonia puffy two thumbs up.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Kurt70@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 3,
  helpful_no: 0,
  appropriate: false
}, {
  id: 33,
  username: "Sine_Pari",
  product_id: 3,
  date: "8 months ago",
  title: "Very comfortable and practical",
  stars: 5,
  review: "Very comfortable and practical jacket for inclement weather conditions, particularly in the mountains. Highly recommended for outdoor enthusiasts and former military types in the SPECOPS community.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Sine_Pari@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 190,
  helpful_no: 6,
  appropriate: false
}, {
  id: 34,
  username: "Bruce",
  product_id: 3,
  date: "15 days ago",
  title: "Just about perfect",
  stars: 4,
  review: "I bought this to travel to the northwest for a week where it's a little colder than Santa Rosa.  Fits perfectly, fits great, and does the job against the cold.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Bruce@hotmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 6,
  helpful_no: 1,
  appropriate: false
}, {
  id: 35,
  username: "img0",
  product_id: 3,
  date: "3 days ago",
  title: "Loses insulation...",
  stars: 2,
  review: "I loved this jacket until few minutes ago. It is warm enough and packs not too bad. However, I noticed tiny, thin threads on it today, so I pulled them thinking they got stuck from a chair... but turned out I'm pulling out the insulation. Through the jacket's fabric. Unfortunately, I'm gonna return it.",
  img: "url",
  caption: "Beautiful color!!",
  recommend: false,
  readReviews: false,
  feedBack: "",
  email: "img0@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 1,
  helpful_yes: 6,
  helpful_no: 1,
  appropriate: false
}, {
  id: 36,
  username: "aaronlee27",
  product_id: 3,
  date: "2 days ago",
  title: "I didn't like it",
  stars: 1,
  review: "It's English made so the men's zipper is on the left. The zipper is cheap and got caught on the back flap repeatedly. The synthetic insulation immediately began pilling through the thin nylon exterior. I returned the jacket after wearing twice.",
  img: "",
  caption: "",
  recommend: false,
  readReviews: true,
  feedBack: "",
  email: "aaronlee27@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 5,
  helpful_yes: 9,
  helpful_no: 2,
  appropriate: false
}, {
  id: 37,
  username: "Mtn_Goat",
  product_id: 3,
  date: "3 years ago",
  title: "Not much to enjoy here...",
  stars: 2,
  review: "Wow...this is lame.  Partly my fault for testing a new brand, but it I'm guessing Craghoppers has never tested their gear or updated sizing style.",
  img: "",
  caption: "",
  recommend: false,
  readReviews: false,
  feedBack: "",
  email: "Mtn_Goat@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 1,
  helpful_yes: 4,
  helpful_no: 0,
  appropriate: false
}, {
  id: 38,
  username: "Justaregularguy",
  product_id: 4,
  date: "6 months ago",
  title: "Very poor design and construction.",
  stars: 1,
  review: `This jacket is warm and comfortable once you get it on. However, you cannot get it on without the zipper getting stuck at least 5 times. The same is true of the pockets too. There is also no cell phone pocket inside or outside (this is a Dec 2018 purchase). I regret not going for a jacket I could try in the store.`,
  img: "",
  caption: "",
  recommend: false,
  readReviews: true,
  feedBack: "",
  email: "Justaregularguy@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 2,
  helpful_yes: 25,
  helpful_no: 3,
  appropriate: false
}, {
  id: 39,
  username: "RomeoTango",
  product_id: 4,
  date: "3 days ago",
  title: "Size is labeled XL but fits like a Medium.",
  stars: 2,
  review: "Total THUMBS DOWN on this product. DO NOT BUY. The sizes are NOT correct for Americans. Maybe some small people is a different country but not NORMAL XL people. This was labeled XL but fits like a Medium.",
  img: "",
  caption: "",
  recommend: false,
  readReviews: false,
  feedBack: "",
  email: "RomeoTango@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 1,
  helpful_yes: 7,
  helpful_no: 5,
  appropriate: false
}, {
  id: 40,
  username: "BlueRidgeWalker",
  product_id: 4,
  date: "1 day ago",
  title: "Great coat for the money",
  stars: 4,
  review: "I bought XL which I also do for other brands.  It fits well and keeps me warm in temps down to about 30.  It may run just slightly smaller than some American brands but for the money, I am very satisfied.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "BlueRidgeWalker@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 35,
  helpful_no: 2,
  appropriate: false
}, {
  id: 41,
  username: "Chinolu",
  product_id: 4,
  date: "16 days ago",
  title: "Light and contuvo and fits perfect",
  stars: 5,
  review: "Is the perfect jacket for this time of the year is light and feels very contable I order a size L I’m 5’6” 147lbs and it fits perfect, no complaints what so ever.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Chinolu@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 9,
  helpful_no: 0,
  appropriate: false
}, {
  id: 42,
  username: "Kevin",
  product_id: 5,
  date: "1 day ago",
  title: "Subpar offering from a company I normally trust",
  stars: 2,
  review: `Purchased this jacket hoping it would be a contender to add to the "go to jacket pile" i have in my closet for cold days. Normally I run an Arc'teryx Atom LT Hoody, or an OR Ferrosi Hoody. This is in the similar price point and was hoping for a winner. Sadly, the zippers and seams around them are poorly put together, and the main front zipper is difficult to negotiate and zip up because the insert pin doesn't slip well into the zipper retaining box easily at all. In terms of feel on the skin, the outside and the inside of the jacket are lined with identical material, making the inside of the sleeves feel rough. Normally I might expect a microfiber fleece lining on parts of the inside of the jacket, or maybe just the pockets. No luck here. The fit is nice, not too slim, not too puffy, but the other negatives along with the current price don't justify the purchase. Will be returning.`,
  img: "",
  caption: "",
  recommend: false,
  readReviews: false,
  feedBack: "",
  email: "Kevin@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 2,
  helpful_yes: 11,
  helpful_no: 2,
  appropriate: false
}, {
  id: 43,
  username: "marinlocal",
  product_id: 5,
  date: "17 days ago",
  title: "Great jacket",
  stars: 5,
  review: "Great look and fit. Packs up easy in it's own pocket, which is great for travel. Incredibly warm and I dig the grey color. Very happy with this jacket.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "marinlocal@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 10,
  helpful_no: 1,
  appropriate: false
}, {
  id: 44,
  username: "Kjsieren",
  product_id: 5,
  date: "1 day ago",
  title: "Great coat!",
  stars: 5,
  review: "Great fit, great weight!  Versatile coat that helps this winter.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Kjsieren@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 30,
  helpful_no: 2,
  appropriate: false
}, {
  id: 45,
  username: "James123",
  product_id: 5,
  date: "2 days ago",
  title: "Warmth and Fit Like a Second Skin",
  stars: 5,
  review: "The wind was blowing hard and my new jacket kept me warm with it's comfortable fit and it felt like a custom design for my body. I love the vision of the maker to create products in a sustainable manner. Thank you, thank you.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "James123@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 3,
  helpful_no: 0,
  appropriate: false
}, {
  id: 46,
  username: "Tommy",
  product_id: 5,
  date: "3 days ago",
  title: "Not sized for athletic build",
  stars: 2,
  review: `This jacket is sized longer than usual, much larger than usual in the stomach, and MUCH smaller than usual in the shoulders/arms. I ordered a medium, and the stomach is probably big enough to fit someone with a 40+" waist, and it's long enough to fit someone 6'6". However, the shoulders and arms are EXTREMELY tight. I assumed that a brand named "Craghoppers" would have a fairly athletic fit, but it's the exact opposite, this is sized for someone tall, wide in the stomach, and scrawny in the arms/shoulders.`,
  img: "",
  caption: "",
  recommend: false,
  readReviews: false,
  feedBack: "",
  email: "Tommy@yahoo.com",
  location: "",
  purchaseLocation: 2,
  fit: 1,
  helpful_yes: 2,
  helpful_no: 1,
  appropriate: false
}, {
  id: 47,
  username: "Trever",
  product_id: 5,
  date: "1 month ago",
  title: "Bargin puffy",
  stars: 4,
  review: `I had been looking for a decent puffy for the colder months for a bit now, but not wanting to break the bank. Then I came across the Craghoppers down jacket on clearance at my local REI. The only one in store was a medium and I typically wear a large (I'm about 5'10 and 170 with a medium/athletic build for reference), but tried on the medium anyways. Overall the jacket fits great, definitely fits more like a large than a medium. I can still wear layers under it when needed, and to wear a layer over it (like a rain jacket) isn't bad either. My first time wearing it out in inclement weather (temps in the teens and strong winds) I was shocked how well it blocked the wind, and it's very warm, especially for not being very bulky.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Trever@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 2,
  helpful_yes: 12,
  helpful_no: 2,
  appropriate: false
}, {
  id: 48,
  username: "herbrewhammer",
  product_id: 5,
  date: "2 months ago",
  title: "lightweight and great material, weird sizing",
  stars: 3,
  review: `I bought this online not sure if it would fit. I'm 5'6" and 160 lbs. My chest is 38" and my waist is 30. I felt like the jacket was snug in the chest, comfortable in the arms and snug on the waist. It was also big in the abdomen. I originally ordered the small which might have been a mistake on my part. The zipper was European and also would snag on the inside constantly. Eventually traded this in for the Rei brand which fit excellent.`,
  img: "",
  caption: "",
  recommend: false,
  readReviews: true,
  feedBack: "",
  email: "herbrewhammer@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 2,
  helpful_yes: 40,
  helpful_no: 1,
  appropriate: false
}, {
  id: 49,
  username: "hiro",
  product_id: 5,
  date: "6 days ago",
  title: "Nice++++",
  stars: 5,
  review: `I think nice item. I need item PATAGONIA.But it' not shipping to Outside US. I recommend the item. It's very worm.`,
  img: "",
  caption: " ",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "hiro@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 2,
  helpful_no: 0,
  appropriate: false
}, {
  id: 50,
  username: "bobloblaw",
  product_id: 5,
  date: "5 days ago",
  title: "It's Warm and Comfortable",
  stars: 4,
  review: `bought this a few days ago right before Chicago's -20 degree weather. It kept me warm where the jacket covers. I mean, what other proof do you need? 
  It's more comfortable than the other jackets I tried out at REI at this price point. The Arcteryx and Patagonia parkas were the only ones that were as comfortable, but they're the in $400-500 price range.
  The only downside is that you can tell they cut corners on the seams like velcro and zippers. They're cheaper but they'll still do the job. For the price, this is a good jacket`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "NWDude@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 3,
  helpful_no: 0,
  appropriate: false
}, {
  id: 51,
  username: "kkamp",
  product_id: 6,
  date: "1 day ago",
  title: "Great 2-in-1 for the money",
  stars: 5,
  review: "Got this jacket in consolation to the twice and expensive North Face. It ticks all the boxes in what I need with great warmth and a durable outer shell. One thing that I wish it had compared to other more expensive jackets is an insulated hood, I only use the hood when absolutely necessary or if I am wearing a beanie.",
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "kkamp@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 40,
  helpful_no: 2,
  appropriate: false
}, {
  id: 52,
  username: "MoSko",
  product_id: 6,
  date: "13 days ago",
  title: "Keeps me warm but has a fatal flaw in my opinion",
  stars: 2,
  review: `So far, this jacket keeps me toasty during the NY winter. I haven't yet had the opportunity to test how "waterproof" this jacket is.`,
  img: "",
  caption: "",
  recommend: false,
  readReviews: false,
  feedBack: "",
  email: "MoSko@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 4,
  helpful_yes: 5,
  helpful_no: 3,
  appropriate: false
}, {
  id: 53,
  username: "Jarnipman",
  product_id: 6,
  date: "4 days ago",
  title: "Best parka on the market for subzero weather",
  stars: 5,
  review: `I love this parka!!!!  This is not only the classiest looking parka (it looks like a cross between a designer bomber jacket and a winter parka), but it is the warmest and best constructed I have ever seen.  I live in MN and I use it in subzero weather all the time with nothing more than a t-shirt and cheap pullover underneath it.  I bought it because the features are unmatched, and the quality is stunning.  Compare it side by side to all other brands and you will see what I’m talking about.  Attached is a photo of me wearing it in -20F with the wind howling and I am very warm.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Jarnipman@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 20,
  helpful_no: 0,
  appropriate: false
}, {
  id: 54,
  username: "Jamie",
  product_id: 6,
  date: "4 days ago",
  title: "IT IS THE BEST JACKET/COAT/PARKA EVER!!!",
  stars: 5,
  review: `IT IS THE BEST JACKET/COAT/PARKA EVER!!! MY WIFE AND I COULDN'T HAVE LIVED WITHOUT IT THIS WINTER IN CAPE COD MASSACHUSETTS!`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Jamie@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 1,
  helpful_no: 0,
  appropriate: false
}, {
  id: 55,
  username: "lasaga",
  product_id: 6,
  date: "7 days ago",
  title: "Better than an expedition parka",
  stars: 5,
  review: `It has been over a year since I bought this coat. I bought it in the REI store in Denver. Before December, it hadn’t really been tested. However, in the days leading to Christmas, it faced a trial in the form of a day at a Washington ski resort. I performed amazingly. It didn’t even get wet when I feel in some snow. Has more powerful fill down than the expedition parka and more of it. Do yourself a favor and buy it.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "lasaga@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 7,
  helpful_no: 1,
  appropriate: false
}, {
  id: 56,
  username: "TAME",
  product_id: 6,
  date: "4 days ago",
  title: "Best parka on the market for subzero weather",
  stars: 5,
  review: `Having just moved to Boston, this is my first real winter coat. Even at -10 degrees, it’s warm enough to spend time outside. The tradeoff is that this jacket is heavy and bulky.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "TAME@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 4,
  helpful_no: 1,
  appropriate: false
}, {
  id: 57,
  username: "Bryan",
  product_id: 6,
  date: "1 year ago",
  title: "Super cozy and lightweight",
  stars: 5,
  review: `I've been wearing this jacket around town for about a week now, and I have to say I'm really impressed with it.  It's incredibly lightweight and comfortable.  I was a little concerned about fit when I ordered it, since sometimes Patagonia is a little unpredictable, bit it's very much true to size. I've walked the dog on a morning in the low 20s, and I've walked back and forth to work in the upper 40s-lower50s, and found it to be exactly the right amount of insulation in all of those settings.  I stayed dry even in some moderate rain/snow mix.  The hood fits great, even without any way to adjust it around the face (has a pull in the back).  Highly recommend.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "Bryan@gmail.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 6,
  helpful_no: 1,
  appropriate: false
}, {
  id: 58,
  username: "TravelerTony",
  product_id: 6,
  date: "8 days ago",
  title: "Lifesaver",
  stars: 5,
  review: `I like the idea of my gear being packable and condensible and this was both! I went hiking for a week in colorado where the temperature in Denver was 90 but on any 14er it was easily 30 degrees and thankfully I had this jacket in my pack otherwise I would have froze! Packs nicely into its pocket and comes out nicely. Hood can be tightened to  seal from the wind getting inside.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "TravelerTony@gmail.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 21,
  helpful_no: 5,
  appropriate: false
}, {
  id: 59,
  username: "J315",
  product_id: 6,
  date: "4 days ago",
  title: "Great Jacket",
  stars: 5,
  review: `I'm 5'10 170LBS. Size M fits perfectly. Everything feels high quality with this jacket. I love it!`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: true,
  feedBack: "",
  email: "J315@yahoo.com",
  location: "",
  purchaseLocation: 2,
  fit: 3,
  helpful_yes: 31,
  helpful_no: 2,
  appropriate: false
}, {
  id: 60,
  username: "Zachary",
  product_id: 6,
  date: "20 days ago",
  title: "Comfortable, Warm",
  stars: 4,
  review: `Love this jacket - it's definitely my go to from freezing temperatures to about 58 degrees. I am 5'11" 165lbs and the medium fits me perfect. There's room to layer with a base layer or fleece without feeling tight. Still constantly surprised by how warm it can keep me with just a t shirt underneath - great for Boston winters. I've taken it to the top of Mt. Rainer, Mt. Washington, and Iceland - solid product.`,
  img: "",
  caption: "",
  recommend: true,
  readReviews: false,
  feedBack: "",
  email: "Zachary@yahoo.com",
  location: "",
  purchaseLocation: 1,
  fit: 3,
  helpful_yes: 1,
  helpful_no: 2,
  appropriate: false
}], (err, results) => {
  if (err) {
    console.log(`mongoose error: ${err}`)
  }
});

module.exports = REI;